### ISSUE TITLE
More options for the FreeDV (int) Reporter

### ISSUE THREAD

**Issue by barjac** [tmiw/ezDV#20]
Since the QST article about FreeDV has been published it has become clear that the reporter needs to have more fine grained setting options.
It's great to see more stations on the bands, but on 20m especially the reporter is becoming difficult to read in use.
Suggestions:
1 A filter to remove calls that have not been updated in the last N mins.
2 An option to only display (or highlight?) calls who have received me in the last N mins).
3 Show my own call line in a different colour.
4 An option to switch the reporter band filter automatically to the currently reported band (but only when that changes). i.e. The reporter band selector would still over-ride.

Just few ideas for discussion ;)

**Comment by tmiw** [comment]
Please create this in the main freedv-gui repo instead as this has to do with functionality in that application. ezDV, while it does support reporting to FreeDV Reporter, has no internal display capability.
