### ISSUE TITLE
Reporting page - add ability to report via reporter the current mode and frequency

### ISSUE THREAD

**Issue by g0kao** [tmiw/ezDV#26]
A thought just came to me as I was using the module with my FTdx10 connected via rear port. The module doesn't report to FreeDV Reporter when being used as we have previously discussed when I was initially testing.
Could the module reporting page where Callsign and Locator are configured be updated to allow entry of Frequency and Mode currently being used?  most people will be using their computer maybe to change modes or just keep an eye on battery levels so would be a useful way of enabling reporting via reporter at the same time for those where the rigs cannot communicate to the module their settings.

**Comment by tmiw** [comment]
Give https://github.com/tmiw/ezDV/releases/tag/20231206 a shot and let me know how it goes. If you have problems with that, I can go ahead and reopen this bug for further investigation.
